#!/bin/sh

echo " +----------------------------------------------------------------------------+"
echo " | Training Wheels Classroom Server.                                          |"
echo " |                                                                            |"
echo " | http://gettrainingwheels.org                                               |"
echo " +----------------------------------------------------------------------------+"
echo
