#!/usr/bin/env ruby

Vagrant::Config.run do |config|
  config.vm.define :trainingwheels do |tw_config|
    tw_config.vm.box         = "precise64"
    tw_config.vm.box_url     = "http://files.vagrantup.com/precise64.box"
    tw_config.vm.host_name   = "training.wheels"

    tw_config.vm.customize ["modifyvm", :id, "--memory", "512"]
    tw_config.vm.customize ["modifyvm", :id, "--cpus", "1"]

    # Shared folders through NFS. This is supported in Mac and Linux. Windows may have
    # issues, see Vagrant site for documentation.
    config.vm.network :hostonly, "10.1.0.2"
    config.vm.share_folder("twdir", "/var/trainingwheels", "../", :nfs => true)

    # We specify a fixed IP address above, so don't use port forwarding, rather make
    # an entry into your /etc/hosts for the actual IP address.
    # tw_config.vm.forward_port

    tw_config.vm.provision :shell, :path => "provision/ansible-setup.sh"
    tw_config.vm.provision :shell, :path => "provision/controller-setup.sh"
    tw_config.vm.provision :shell, :path => "provision/dev-setup.sh"

    # Load a local setup file if it exists, so you can use it to
    # provide additional provisioning steps.
    if File.exist?(File.join(File.dirname(__FILE__), "setup.local.sh"))
      tw_config.vm.provision :shell, :path => "setup.local.sh"
    end
  end
end
