# Controller settings for EC2.

---
# The vagrant provisioner logs in as root, so we need to specify the admin
# user's home location.
admin_user_home: '/home/ubuntu'

# www.conf for php-fpm
# Only the nginx user is allowed to write or read from the php-fpm socket.
phpfpm_user: 'phpfpm'
phpfpm_group: 'phpfpm'
phpfpm_pm_start_servers: '2'
phpfpm_listen: '/run/phpfpm.sock'
phpfpm_listen_owner: 'nginx'
phpfpm_listen_group: 'nginx'
phpfpm_listen_mode: '0600'

# nginx
nginx_user: 'nginx'
nginx_server_name: 'tw-build.com'
nginx_lan_subnet: '192.168.0.0/16'
nginx_worker_processes: '1'
nginx_webroot: '/var/trainingwheels/controller/web'

# mongodb
mongo_root_password: 'rLiNC7jGeV'
mongo_app_password: 'aYP0k8GQTQ'
mongo_restart_timeout: 120

# php.ini for php-fpm
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'America/Chicago'
php_cgi_fix_pathinfo: '0'
php_short_open_tag: 'Off'

# apc.ini
apc_rfc1867: '1'
apc_shm_size: '96M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# application
app_user: 'tw'
app_pass: 'bIvymOPiWShE1Xj'
