##
# Ansible playbook for setting up a Training Wheels server in EC2, for
# our auto build system.
#

---
- hosts: all
  gather_facts: False

  vars:
    twdir: '/var/trainingwheels'

  tasks:
    ##
    # Update the machine
    #
    - name: Update apt
      action: apt update-cache=yes

    - name: Change the hostname in /etc/hosts
      action: copy src=etc-hosts dest=/etc/hosts owner=root group=root mode=0644

    - name: Change the hostname in /etc/hostname
      action: copy src=etc-hostname dest=/etc/hostname owner=root group=root mode=0644

    - name: Change the hostname using the hostname command
      action: command hostname tw-build.com

    - name: Install required packages for Jenkins slave and general use
      action: apt pkg=$item state=installed
      with_items:
        - git
        - openjdk-7-jre-headless

    # We must setup the bender user after doing the Java install, otherwise
    # Jenkins will build it's own version of Java as the slave connects.
    - name: Create bender group
      action: group name=bender

    - name: Create bender user for Jenkins to connect with
      action: "user name=bender home=/home/bender groups=admin,bender group=bender shell=/bin/bash"

    - name: SSH folder for bender
      action: file path=/home/bender/.ssh state=directory owner=bender group=bender mode=755

    - name: Copy authorized keys for bender
      action: copy src=bender_authorized_keys dest=/home/bender/.ssh/authorized_keys owner=bender group=bender mode=644

    # Training Wheels app download and setup
    - name: Clone the repo
      action: git repo=https://github.com/trainingwheels/trainingwheels.git dest=$twdir version=master

    - name: Let web user write to log file directory
      action: file state=directory path=$twdir/controller/log mode=0777
