#!/bin/bash

# User input
# EC2_EXTERNAL: if this is being run from a server within EC2, say a control box,
# it's faster to use the internal IP address, so the default behavior is to assume
# internal. However, for testing, it may be necessary to run from outside of EC2
# so you can override by passing the parameter 'external'.
EC2_EXTERNAL="$1"

# Vars
TAG_VAL='trainingwheels-autobuild'
IP_ADDRESS='184.73.222.124'
KEY_NAME='tw'
RUNNING_TIMEOUT='120'
INSTANCE_TYPE='m1.small'
REGION='us-east-1'
BASE_DIR=`pwd`
AMI='ami-3d4ff254'
ID_FILE="${HOME}/.ssh/tw.pem"
ANS_ARGS="-c ssh -s --timeout=$RUNNING_TIMEOUT --private-key=$ID_FILE --inventory-file=$BASE_DIR/ec2-hostname"
SLEEP='3'
CUSTOM_HOST='tw-build.com'

echo ''
echo 'Finding all existing build instances...'
OBSOLETE_INSTANCES=`euca-describe-instances --filter tag-value=$TAG_VAL | grep INSTANCE | cut -f 2`

echo ''
echo "The following instances will be terminated:"
echo "$OBSOLETE_INSTANCES"
euca-terminate-instances $OBSOLETE_INSTANCES

echo ''
echo "Waiting for all build instances to be shut down..."
if ! timeout $RUNNING_TIMEOUT sh -c "while euca-describe-instances --filter tag-value=$TAG_VAL | grep INSTANCE | grep -qv terminated; do echo 'checking...'; sleep $SLEEP; done"; then
  echo "server didn't shutdown within $RUNNING_TIMEOUT seconds"
  exit 1
fi

echo ''
echo 'Creating new instance...'
NEW_INSTANCE_ID=`euca-run-instances --key $KEY_NAME --region $REGION --instance-type $INSTANCE_TYPE --group default $AMI | grep INSTANCE | cut -f 2`

echo ''
echo "Waiting for the instance to have state 'running'..."
if ! timeout $RUNNING_TIMEOUT sh -c "while ! euca-describe-instances $NEW_INSTANCE_ID | grep -q running; do echo 'checking...'; sleep $SLEEP; done"; then
  echo "server didn't become active within $RUNNING_TIMEOUT seconds"
  exit 1
fi

echo ''
echo "Tagging new instance $NEW_INSTANCE_ID with tag $TAG_VAL..."
euca-create-tags --tag tw-usage=$TAG_VAL $NEW_INSTANCE_ID

# We keep a single elastic public IP address. Assign this address to the instance.
echo ''
echo 'Associating the elastic IP with the new instance...'
euca-associate-address -i $NEW_INSTANCE_ID $IP_ADDRESS

echo ''
echo 'Grabbing the internal host name if required, else the external...'
if [ "$EC2_EXTERNAL" != 'external' ]; then
  HOST=`euca-describe-instances $NEW_INSTANCE_ID | grep internal | cut -f 5`
else
  HOST="$CUSTOM_HOST"
fi
echo "$HOST" > $BASE_DIR/ec2-hostname
echo "$HOST"

echo ''
echo "Waiting for the instance to actually accept ssh connections..."
if ! timeout $RUNNING_TIMEOUT sh -c "while ! ssh ubuntu@$HOST 'whoami' | grep 'ubuntu'; do echo 'checking...'; sleep $SLEEP; done"; then
  echo "server didn't start after $RUNNING_TIMEOUT seconds"
  exit 1
fi

echo ''
echo "Waiting for the instance to gain internal networking..."
if ! timeout $RUNNING_TIMEOUT sh -c "while ! ssh ubuntu@$HOST 'ping -c4 $REGION.ec2.archive.ubuntu.com' | grep '64 bytes from'; do echo 'checking...'; sleep $SLEEP; done"; then
  echo "server internal networking didn't start after $RUNNING_TIMEOUT seconds"
  exit 1
fi

echo ''
echo "Waiting for the instance to gain external networking..."
if ! timeout $RUNNING_TIMEOUT sh -c "while ! ssh ubuntu@$HOST 'ping -c4 security.ubuntu.com' | grep '64 bytes from'; do echo 'checking...'; sleep $SLEEP; done"; then
  echo "server external networking didn't start after $RUNNING_TIMEOUT seconds"
  exit 1
fi

echo ''
echo "Running initial build and setup phase playbook..."
if ! ansible-playbook $ANS_ARGS ./prep-server.yml; then
  exit 1
fi

echo ''
echo 'Copying the settings files for the controller playbooks...'
cp $BASE_DIR/controller-settings-ec2.yml $BASE_DIR/../playbooks/controller/settings.yml

echo ''
echo 'Running controller setup and sample data playbooks...'
cd $BASE_DIR/../playbooks/controller
if ! ansible-playbook $ANS_ARGS setup.yml; then
  exit 1
fi
if ! ansible-playbook $ANS_ARGS sample-data.yml; then
  exit 1
fi
echo ''
echo 'Running the post build playbook...'
cd $BASE_DIR
if ! ansible-playbook $ANS_ARGS post-build.yml; then
  exit 1
fi
echo ''
echo 'done.'
echo ''
