# Settings that are applied to the templates.

---
# Hostname is important as we need to delete an anonymous MySQL
# user that is created with this name, make sure you match this
# up.
server_hostname: 'gettrainingwheels.com'

# php.ini for apache2
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'America/Chicago'
php_short_open_tag: 'Off'

# apc.ini
apc_rfc1867: '1'
apc_shm_size: '256M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# my.cnf
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'

# mysql
# this password must also appear in the prep-server.yml file.
mysql_root_password: 'tplqomnscy323e'

# apache
apache_server_admin: 'mark@fourkitchens.com'
apache_server_alias: '*.*.gettrainingwheels.com'
apache_servername: 'gettrainingwheels.com'

# apache virtual document roots, these two are closely related.
apache_virtual_docroot: '/home/%-4/www/%-3'
apache_directory: '/home/*/www/*'

# vsftpd
vsftpd_anonymous_enable: 'NO'
vsftpd_local_enable: 'YES'
vsftpd_write_enable: 'YES'
vsftpd_local_umask: '002'
