##
# Ansible playbook for allowing root login on Ubuntu server.
#

---
- hosts: all
  gather_facts: False
  sudo: True

  tasks:
    - name: Copy the authorized keys from ubuntu user to root user so we can login
      action: command cp /home/ubuntu/.ssh/authorized_keys /root/.ssh/authorized_keys
