#!/bin/sh

# Script for running the play on the localhost.
# Tags reference:
#
# common: Common components for the LAMP stack.
# nodejs: Install the node.js server.
#
ansible-playbook --tags="common" -c local ./setup.yml
