#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use TrainingWheels\Console\UserRetrieve;
use TrainingWheels\Console\UserCreate;
use TrainingWheels\Console\UserDelete;
use TrainingWheels\Console\ResourceCreate;
use TrainingWheels\Console\ResourceDelete;
use TrainingWheels\Console\ResourceSync;
use TrainingWheels\Log\Log;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use Symfony\Component\Console\Application;

$log = new Logger('tw');
$log->pushHandler(new StreamHandler('../log/cli.log', Logger::DEBUG));

Log::$instance = new Log($log);
Log::log('Initializing CLI application', L_INFO);

$application = new Application();
$application->add(new UserRetrieve);
$application->add(new UserCreate);
$application->add(new UserDelete);
$application->add(new ResourceCreate);
$application->add(new ResourceDelete);
$application->add(new ResourceSync);
$application->run();
