#!/usr/bin/env php
<?php

$app = require_once __DIR__ . '/bootstrap.php';

use Monolog\Logger;
use Monolog\Formatter\LineFormatter;
use Monolog\Handler\StreamHandler;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use TrainingWheels\Log\Log;
use TrainingWheels\Console\UserRetrieve;
use TrainingWheels\Console\UserCreate;
use TrainingWheels\Console\UserDelete;
use TrainingWheels\Console\ResourceCreate;
use TrainingWheels\Console\ResourceDelete;
use TrainingWheels\Console\ResourceSync;

$formatter = new LineFormatter("[%datetime%] %channel%.%level_name%: %message% \n");
$stream = new StreamHandler(__DIR__.'/../log/cli.log', Logger::DEBUG);
$stream->setFormatter($formatter);
$log = new Logger('tw');
$log->pushHandler($stream);

Log::$instance = new Log($log);
Log::log('Initializing CLI application', L_INFO);

$console = new Application();
$console->add(new UserRetrieve($app));
$console->add(new UserCreate($app));
$console->add(new UserDelete($app));
$console->add(new ResourceCreate($app));
$console->add(new ResourceDelete($app));
$console->add(new ResourceSync($app));

$console->run();
