#!/usr/bin/env php
<?php

$autoloader_path = __DIR__.'/../vendor/autoload.php';

if (!file_exists($autoloader_path)) {
  print 'Unable to find the class autoloader, are you sure you have run "composer install"? See README.md for more information.' . "\n";
  exit;
}

$whoami = exec('whoami');
if ($whoami !== 'root') {
  print 'This command must be run as root or using "sudo".' . "\n";
  exit;
}

require_once $autoloader_path;

use TrainingWheels\Console\UserRetrieve;
use TrainingWheels\Console\UserCreate;
use TrainingWheels\Console\UserDelete;
use TrainingWheels\Console\ResourceCreate;
use TrainingWheels\Console\ResourceDelete;
use TrainingWheels\Console\ResourceSync;
use TrainingWheels\Log\Log;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use Symfony\Component\Console\Application;

$log = new Logger('tw');
$log->pushHandler(new StreamHandler('../log/cli.log', Logger::DEBUG));

Log::$instance = new Log($log);
Log::log('Initializing CLI application', L_INFO);

$application = new Application();
$application->add(new UserRetrieve);
$application->add(new UserCreate);
$application->add(new UserDelete);
$application->add(new ResourceCreate);
$application->add(new ResourceDelete);
$application->add(new ResourceSync);
$application->run();
